titancore/capstone/Controllers/CrewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using capstone.Data;
using capstone.Models;
using Microsoft.AspNetCore.Authorization;

namespace capstone.Controllers
{
    public class CrewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CrewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Crews
        [Authorize]
        public IActionResult Index()
        {
            var allCrews = _context.Crew
                .Include(m => m.EmployeeType)
                .ToList()
                .Select(c => new Crew
            {
                CrewId = c.CrewId,
                ProjectId = c.ProjectId,
                EmployeeTypeId = c.EmployeeTypeId,
                EmployeeType = c.EmployeeType,
                PayRate = c.PayRate,
                EmployeeQuantity = c.EmployeeQuantity
            });
            return View(allCrews);
        }

        // GET: Crews/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crew = await _context.Crew
                .FirstOrDefaultAsync(m => m.CrewId == id);
            if (crew == null)
            {
                return NotFound();
            }

            return View(crew);
        }

        // GET: Crews/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectNumber");
            ViewData["EmployeeTypeId"] = new SelectList(_context.EmployeeType, "EmployeeTypeId", "Category");
            return View();
        }

        // POST: Crews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("CrewId,ProjectId,EmployeeTypeId,PayRate,EmployeeQuantity")] Crew crew)
        {
            if (ModelState.IsValid)
            {
                var ProjectId = crew.ProjectId;
                _context.Add(crew);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Projects", new { id = ProjectId });
            }
            ViewData["ProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectNumber");
            ViewData["EmployeeTypeId"] = new SelectList(_context.EmployeeType, "EmployeeTypeId", "Category");
            return View(crew);
        }

        // GET: Crews/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crew = await _context.Crew.FindAsync(id);
            if (crew == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectNumber");
            ViewData["EmployeeTypeId"] = new SelectList(_context.EmployeeType, "EmployeeTypeId", "Category");
            return View(crew);
        }

        // POST: Crews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("CrewId,ProjectId,EmployeeTypeId,PayRate,EmployeeQuantity")] Crew crew)
        {
            var ProjectId = crew.ProjectId;
            if (id != crew.CrewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var editCrew = await _context.Crew.FindAsync(id);
                    editCrew.ProjectId = crew.ProjectId;
                    editCrew.EmployeeTypeId = crew.EmployeeTypeId;
                    editCrew.PayRate = crew.PayRate;
                    editCrew.EmployeeQuantity = crew.EmployeeQuantity;
                    _context.Update(editCrew);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CrewExists(crew.CrewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Projects", new { id = ProjectId });
            }
            ViewData["ProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectNumber");
            ViewData["EmployeeTypeId"] = new SelectList(_context.EmployeeType, "EmployeeTypeId", "Category");
            return View(crew);
        }

        // GET: Crews/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crew = await _context.Crew
                .FirstOrDefaultAsync(m => m.CrewId == id);
            if (crew == null)
            {
                return NotFound();
            }

            return View(crew);
        }

        // POST: Crews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crew = await _context.Crew.FindAsync(id);
            var ProjectId = crew.ProjectId;
            _context.Crew.Remove(crew);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Projects", new { id = ProjectId });
        }

        private bool CrewExists(int id)
        {
            return _context.Crew.Any(e => e.CrewId == id);
        }
    }
}

titancore/capstone/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using capstone.Data;
using capstone.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace capstone.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProjectsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Projects
        [Authorize]
        public IActionResult Index()
        {
            // Showing two different kinds of ways to do ".Include()"
            var allProjects = _context.Project
                .Include("Client")
                .Include(p => p.LineItems)
                .ToList()
                .Select(p => new Project
                {
                    ProjectId = p.ProjectId,
                    UserId = p.UserId,
                    ClientId = p.ClientId,
                    Client = p.Client,
                    ProjectNumber = p.ProjectNumber,
                    WorkDay = p.WorkDay,
                    SalesTax = p.SalesTax,
                    CompletionDate = p.CompletionDate,
                    IsCompleted = p.IsCompleted,
                    TimeTrackerId = p.TimeTrackerId,
                    TotalMaterialCost = p.LineItems.Sum(m => m.MaterialCost),
                    TotalMaterialQuote = p.LineItems.Sum(m => m.MaterialQuote),
                    TotalSubCost = p.LineItems.Sum(m => m.SubCost),
                    TotalSubQuote = p.LineItems.Sum(m => m.SubQuote),
                    TotalManHours = p.LineItems.Sum(m => m.ManHours),
                });

            return View(allProjects);
        }

        // GET: Projects/Details/5
        [Authorize]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allProjects = _context.Project
                .Include("Client")
                .Include(p => p.CrewMembers)
                .ThenInclude(c => c.EmployeeType)
                .Include(p => p.LineItems)
                .Where(m => m.ProjectId == id)
                .ToList()
                .Select(p => new Project
                {
                    ProjectId = p.ProjectId,
                    UserId = p.UserId,
                    ClientId = p.ClientId,
                    Client = p.Client,
                    LineItems = p.LineItems,
                    CrewMembers = p.CrewMembers,
                    ProjectNumber = p.ProjectNumber,
                    SubmittedDate = p.SubmittedDate,
                    ExpirationDate = p.ExpirationDate,
                    WorkDay = p.WorkDay,
                    SalesTax = p.SalesTax,
                    CrewSize = p.CrewMembers.Sum(m => m.EmployeeQuantity),
                    CompletionDate = p.CompletionDate,
                    IsCompleted = p.IsCompleted,
                    TimeTrackerId = p.TimeTrackerId,
                    TotalMaterialCost = p.LineItems.Sum(m => m.MaterialCost),
                    TotalMaterialQuote = p.LineItems.Sum(m => m.MaterialQuote),
                    TotalSubCost = p.LineItems.Sum(m => m.SubCost),
                    TotalSubQuote = p.LineItems.Sum(m => m.SubQuote),
                    TotalManHours = p.LineItems.Sum(m => m.ManHours),
                })
                .FirstOrDefault();

                allProjects.LineItems = allProjects.LineItems
                .Select(li => new LineItem
                {
                    LineItemId = li.LineItemId,
                    ProjectId = li.ProjectId,
                    Project = li.Project,
                    Description = li.Description,
                    MaterialCost = li.MaterialCost,
                    SubCost = li.SubCost,
                    ManHours = li.ManHours,
                    LaborCost = li.ManHours * allProjects.UnburdenedRate,
                    LaborQuote = (li.ManHours * allProjects.UnburdenedRate) * (1 + allProjects.LaborMargin),
                    QuoteSalesTax = li.MaterialQuote * allProjects.ProjectSalesTax
                }).ToList();

                allProjects.CrewMembers = allProjects.CrewMembers
                .Select(c => new Crew
                {
                    CrewId = c.CrewId,
                    ProjectId = c.ProjectId,
                    EmployeeTypeId = c.EmployeeTypeId,
                    EmployeeType = c.EmployeeType,
                    PayRate = c.PayRate,
                    EmployeeQuantity = c.EmployeeQuantity,
                    LaborHours = c.IsManagement ? 0 : c.EmployeeQuantity * allProjects.WorkDay * allProjects.WorkingDays,
                    ManagmentHours = c.IsManagement ? c.EmployeeQuantity * allProjects.WorkDay * allProjects.WorkingDays : 0,
                }).ToList();

                allProjects.TotalCrewLaborHours = allProjects.CrewMembers.Sum(m => m.LaborHours);
                allProjects.TotalCrewLaborCost = allProjects.CrewMembers.Sum(m => m.LaborCost);
                allProjects.TotalCrewManagementHours = allProjects.CrewMembers.Sum(m => m.ManagmentHours);
                allProjects.TotalCrewManagementCost = allProjects.CrewMembers.Sum(m => m.ManagmentCost);

                allProjects.LineItems = allProjects.LineItems
                .Select(li => new LineItem
                {
                    LineItemId = li.LineItemId,
                    ProjectId = li.ProjectId,
                    Project = li.Project,
                    Description = li.Description,
                    MaterialCost = li.MaterialCost,
                    SubCost = li.SubCost,
                    ManHours = li.ManHours,
                    LaborCost = li.ManHours * allProjects.UnburdenedRate,
                    LaborQuote = (li.ManHours * allProjects.UnburdenedRate) * (1 + allProjects.LaborMargin),
                    QuoteSalesTax = li.MaterialQuote * allProjects.ProjectSalesTax
                }).ToList();

            if (allProjects == null)
            {
                return NotFound();
            }

            return View(allProjects);
        }

        // GET: Projects/Create
        [Authorize]
        public IActionResult Create()
        {
           ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FullName");
           ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ProjectId,UserId,ClientId,ProjectNumber,LineItemId,SubmittedDate,ExpirationDate,CompletionDate,IsCompleted,TimeTrackerId")] Project project)
        {
            var user = await GetCurrentUserAsync();

            if (user != null)
            {
                project.UserId = user.Id;
                project.IsCompleted = false;
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FullName", project.ClientId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", project.UserId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FullName", project.ClientId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", project.UserId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,UserId,ClientId,ProjectNumber,WorkDay,SalesTax,SubmittedDate,ExpirationDate,IsCompleted,CompletionDate")] Project project)
        {
            var ProjectId = project.ProjectId;
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var editProject = await _context.Project.FindAsync(id);
                    editProject.ProjectNumber = project.ProjectNumber;
                    editProject.ClientId = project.ClientId;
                    editProject.WorkDay = project.WorkDay;
                    editProject.SalesTax = project.SalesTax;
                    editProject.SubmittedDate = project.SubmittedDate;
                    editProject.ExpirationDate = project.ExpirationDate;
                    editProject.IsCompleted = project.IsCompleted;
                    editProject.CompletionDate = project.CompletionDate;

titancore/capstone/Views/Projects/Create.cshtml
@model capstone.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectNumber" class="control-label"></label>
                <input asp-for="ProjectNumber" class="form-control" />
                <span asp-validation-for="ProjectNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                &nbsp&nbsp&nbsp
                <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

titancore/capstone/Views/Projects/Details.cshtml
@model capstone.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h2>Project Details</h2>
<br />

<div>
    <h3>Project @Html.DisplayFor(model => model.ProjectNumber)</h3>
    <br />
    <div>
        <a asp-action="Index" class="btn btn-default">Back</a>
        &nbsp&nbsp&nbsp
        <a asp-action="Edit" asp-route-id="@Model.ProjectId" class="btn btn-primary">Edit</a>
        <a asp-area="" asp-controller="Projects" asp-action="Quote" asp-route-id="@Model.Client.ClientId" class="btn btn-primary pull-right">View Quote</a>
    </div>
    <hr />
    <h4>Client Contact</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Client
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Client.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Client.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Client.StreetAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsCompleted)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CompletionDate)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a asp-area="" asp-controller="Clients" asp-action="Details" asp-route-id="@Model.Client.ClientId" class="btn btn-primary">@Html.DisplayFor(model => model.Client.FullName)</a>
                </td>
                <td>
                    @Html.DisplayFor(model => model.Client.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Client.Email)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Client.StreetAddress) @Html.DisplayFor(model => model.Client.City), @Html.DisplayFor(model => model.Client.State) @Html.DisplayFor(model => model.Client.ZipCode)
                </td>
                <td>
                    @String.Format("{0:c}", Model.IsCompleted)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CompletionDate)
                </td>
            </tr>
        </tbody>
    </table>
    <h4>Project Info</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectSalesTax)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnburdenedRate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LaborMargin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubmittedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpirationDate)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @String.Format("{0:P2}", Model.ProjectSalesTax)
                </td>
                <td>
                    @String.Format("{0:c}", Model.UnburdenedRate)
                </td>
                <td>
                    @String.Format("{0:P0}", Model.LaborMargin)
                </td>
                <td>
                    @Html.DisplayFor(model => model.SubmittedDate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ExpirationDate)
                </td>
            </tr>
        </tbody>
    </table>
    <h4>Workforce Calculator</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.WorkDay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WorkingDays)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Expected @Html.DisplayFor(model => model.WorkDay) hours per day.
                </td>
                <td>
                    @String.Format("{0:n2}", Model.WorkingDays)

                </td>
            </tr>
        </tbody>
    </table>
    <a asp-controller="Crews" asp-action="Create" class="btn btn-success">Add Member</a>
    <table class="table">
        <thead>
            <tr>
                <th>Crew Size</th>
                <th>Crew Type</th>
                <th>Labor Hours</th>
                <th>Management Hours</th>
                <th>Pay Rate</th>
                <th>Labor Cost</th>
                <th>Management Cost</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Crew c in Model.CrewMembers)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(Model => c.EmployeeQuantity)
                    </td>
                    <td>
                        @Html.DisplayFor(Model => c.EmployeeType.Category)
                    </td>
                    <td>
                        @String.Format("{0:n2}", c.LaborHours)
                    </td>
                    <td>
                        @String.Format("{0:n2}", c.ManagmentHours)
                    </td>
                    <td>
                        @String.Format("{0:c}", c.PayRate)
                    </td>
                    <td>
                        @String.Format("{0:c}", c.LaborCost)
                    </td>
                    <td>
                        @String.Format("{0:c}", c.ManagmentCost)
                    </td>
                    <td>
                        <a asp-controller="Crews" asp-action="Edit" asp-route-id="@c.CrewId" class="lineItembtn btn btn-primary">Edit</a>
                        &nbsp&nbsp&nbsp
                        <a asp-controller="Crews" asp-action="Delete" asp-route-id="@c.CrewId" class="lineItembtn btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
            <tr>
                <th>Totals</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <tr>
                <th>
                    @Html.DisplayFor(Model => Model.CrewSize)
                </th>
                <th></th>
                <th>
                    @String.Format("{0:n2}", Model.TotalCrewLaborHours)
                </th>
                <th>
                    @String.Format("{0:n2}", Model.TotalCrewManagementHours)
                </th>
                <th></th>
                <th>
                    @String.Format("{0:c}", Model.TotalCrewLaborCost)
                </th>
                <th>
                    @String.Format("{0:c}", Model.TotalCrewManagementCost)
                </th>
                <th></th>
            </tr>
        </tbody>
    </table>
    <h4>Totals</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TotalMaterialCost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalMaterialMargin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalMaterialQuote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalSubCost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalSubMargin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalSubQuote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalManHours)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalLaborCost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LaborMargin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalLaborQuote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalSalesTax)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GrandTotal)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @String.Format("{0:c}", Model.TotalMaterialCost)
                </td>
                <td>
                    @String.Format("{0:P0}", Model.TotalMaterialMargin)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalMaterialQuote)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalSubCost)
                </td>
                <td>
                    @String.Format("{0:P0}", Model.TotalSubMargin)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalSubQuote)
                </td>
                <td>
                    @Html.DisplayFor(model => model.TotalManHours)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalLaborCost)
                </td>
                <td>
                    @String.Format("{0:P0}", Model.LaborMargin)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalLaborQuote)
                </td>
                <td>
                    @String.Format("{0:c}", Model.TotalSalesTax)
                </td>
                <td>
                    @String.Format("{0:c}", Model.GrandTotal)
                </td>
            </tr>
        </tbody>
    </table>
    <h4>Line Items</h4>
    <a asp-controller="LineItems" asp-action="Create" class="btn btn-success">Add Item</a>
    @foreach (LineItem li in Model.LineItems)
    {
        <div class="lineitems">
            <h4>@String.Format("{0:c}", li.Description)</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Material Cost
                        </th>
                        <th>
                            Material Margin
                        </th>
                        <th>
                            Material Quote
                        </th>
                        <th>
                            Subcontractor Cost
                        </th>
                        <th>
                            Subcontractor Margin
                        </th>
                        <th>
                            Subcontractor Quote
                        </th>
                        <th>
                            ManHours
                        </th>
                        <th>
                            Labor Cost
                        </th>
                        <th>
                            Labor Quote
                        </th>
                        <th>
                            Sales Tax
                        </th>
                        <th>
                            Total (ex. Sales Tax)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @String.Format("{0:c}", li.MaterialCost)
                        </td>
                        <td>
                            @String.Format("{0:P0}", li.MaterialMargin)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.MaterialQuote)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.SubCost)
                        </td>
                        <td>
                            @String.Format("{0:P0}", li.SubMargin)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.SubQuote)
                        </td>
                        <td>
                            @Html.DisplayFor(Model => li.ManHours)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.LaborCost)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.LaborQuote)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.QuoteSalesTax)
                        </td>
                        <td>
                            @String.Format("{0:c}", li.Total)
                        </td>

                    </tr>
                </tbody>
            </table>
            <div>
                <a asp-controller="LineItems" asp-action="Edit" asp-route-id="@li.LineItemId" class="lineItembtn btn btn-primary">Edit</a>
                &nbsp&nbsp&nbsp
                <a asp-controller="LineItems" asp-action="Delete" asp-route-id="@li.LineItemId" class="lineItembtn btn btn-danger">Delete</a>
            </div>
        </div>
    }
</div>